FROM library/php:7.4.3-apache
MAINTAINER wooyg@wooyg.com

RUN apt -y -qq update
RUN apt install -y -qq libpng-dev libjpeg-dev
RUN echo "ServerName localhost" \
    | tee /etc/apache2/conf-available/servername.conf
RUN docker-php-ext-configure gd --with-jpeg \
&& docker-php-ext-install gd
RUN apt install -y -qq mariadb-client
RUN apt install -y libssl-dev openssl
RUN apt install -y libonig-dev

RUN docker-php-ext-install mbstring
RUN docker-php-ext-install mysqli
RUN docker-php-ext-install pdo
RUN docker-php-ext-install pdo_mysql
RUN docker-php-ext-install opcache
RUN docker-php-ext-install phar

RUN a2enconf servername
RUN a2enmod rewrite
RUN apache2ctl -k graceful

WORKDIR /var/www/html
RUN chmod 707 /var/www/html

RUN apt clean \
  && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

EXPOSE 80
